### PR TITLE
Add env variable for `preUpdatePath` and `postUpdatePath`

### PR DESCRIPTION
**Pull request by SRv6d**
Add environment variables to allow changing the apt timestamp file paths

### CODE REVIEW

**Review by margau — DISMISSED** [review]

**Comment by margau** [comment]
Hi,
thanks for the PR!
Could you fix the lint errors, and add a little bit of usage documentation to the readme?

**Review by margau — APPROVED** [review]

**Comment by SRv6d** [comment]
Sure thing, although a line length of `79` seems to be a bit restrictive and can lead to unnecessarily ugly code. `88`([black](https://github.com/psf/black) default) is often used to give a bit more room.

**Comment by SRv6d** [comment]
@margau Could you create a new release with the changes on pypi.org ?

**Comment by margau** [comment]
I've created an rc: https://pypi.org/project/pkg-exporter/0.2.7rc0/

**Pull request merged**
